### ISSUE TITLE
getApplicationContext() error when instrumentation testing a service that uses a broadcast receiver

### ISSUE THREAD

**Issue by arsSomnium** [karczews/RxBroadcastReceiver#10]
Hi there,

I have a service that uses a broadcast receiver (RxBroadcastReceiver) for communication. While testing this service with junit4 in an instrumentation test I get an getApplicaitonContext() Nullpointer exception while trying to register the receiver. Is there any advice or help to have the test working?
Any help would be highly appreciated.

**Comment by karczews** [comment]
No response for 4 months. closing.
