### ISSUE TITLE
Need maven version update

### ISSUE THREAD

**Issue by MaxMyalkin** [karczews/RxBroadcastReceiver#9]
The latest versions are unavailable at Maven, but Jetpack often fails with connection errors

**Comment by karczews** [comment]
Hi,
latest version is 1.0.4 and I see its available:
https://repo.maven.apache.org/maven2/com/github/karczews/rx2-broadcast-receiver/1.0.4/

What do you mean by "Jetpack" ?

**Comment by MaxMyalkin** [comment]
Thanks
I use `1.0.5-SNAPSHOT` version as you suggest in #6. 
But in my project I'm using `jitpack` repositories too.
Sometimes gradle try to load dependency from `https://jitpack.io/com/github/karczews/rx2-broadcast-receiver/1.0.5-SNAPSHOT` but it fails. Probably jitpack somehow conflicts with `oss.sonatype.org`

**Comment by karczews** [comment]
I think gradle normally tries to lookup dependency in all repositories you define. Anyway, just use 1.0.5 (not snapshot) now.
Cheers.
